# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=60)),
                ('user', models.CharField(max_length=60)),
            ],
        ),
    ]
