# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photolocation_map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='immage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=60)),
                ('user', models.CharField(max_length=60)),
                ('file', models.ImageField(upload_to='pictures')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
