# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photolocation_map', '0004_auto_20170618_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='id',
            field=models.BigIntegerField(auto_created='True', primary_key=True, serialize=False),
        ),
    ]
