# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photolocation_map', '0006_auto_20170618_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
