# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photolocation_map', '0007_auto_20170618_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadfile',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='image',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
