# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 21:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photolocation_map', '0010_auto_20170620_0003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadfile',
            old_name='image',
            new_name='file',
        ),
    ]
